platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: TodoApi

outputs:
- name: TodoApi-Build
- name: TodoApi-Publish

run:
  path: sh
  args: 
  - -exc
  - |
    # Build
    cd TodoApi
    TodoApi.CI/build.sh
    cd ..
    
    # Output for publishing
    mkdir -p TodoApi-Publish/TodoApi/bin/Debug/netcoreapp2.0/publish
    mv TodoApi/TodoApi/bin/Debug/netcoreapp2.0/publish/* TodoApi-Publish/TodoApi/bin/Debug/netcoreapp2.0/publish/
    mv TodoApi/TodoApi.Deploy TodoApi-Publish/
    
    # Output for testing
    mv TodoApi/* TodoApi-Build/