platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: TodoApi

outputs:
- name: TodoApi-Build

run:
  path: sh
  args: 
  - -exc
  - |
    # Build
    cd TodoApi
    TodoApi.CI/build.sh
    cd ..
    
    # Output for testing
    mv TodoApi/* TodoApi-Build/