resources:
  - name: TodoApi
    type: git
    source:
      uri: https://github.com/xtreme-conor-nosal/dotnet-todo-rampup.git
      branch: master
      
  - name: cloud-foundry-stage
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-email}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      
  - name: cloud-foundry-prod
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-email}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      current_app_name: cnosal-todo-api
      
  - name: gh-draft
    type: github-release
    source:
      owner: {{git-owner}}
      repository: {{git-repo}}
      access_token: {{git-token}}
      drafts: true
      
  - name: gh-release
    type: github-release
    source:
      owner: {{git-owner}}
      repository: {{git-repo}}
      access_token: {{git-token}}
      release: true

jobs:
- name: build_test_package
  plan:
  - get: TodoApi
    trigger: true
  - task: build
    file: TodoApi/TodoApi.CI/build.yml
  - task: test
    file: TodoApi/TodoApi.CI/test.yml
  - task: package
    file: TodoApi/TodoApi.CI/package.yml
  - put: gh-draft
    params:
      name: TodoApi-Archive/tag
      tag: TodoApi-Archive/tag
      globs:
      - TodoApi-Archive/todo-api.tar
      
- name: deploy_staging
  serial: true
  serial_groups: [staging]
  plan:
  - get: TodoApi
  - get: gh-draft
    trigger: true
    passed: [build_test_package]
  - task: unzip
    file: TodoApi/TodoApi.CI/unzip-draft.yml
  - put: cloud-foundry-stage
    params:
      manifest: TodoApi-Publish/TodoApi.Deploy/cloud-foundry-staging.yml
      
- name: smoke_staging
  serial: true
  serial_groups: [staging]
  plan:
  - get: TodoApi
  - get: cloud-foundry-stage
    trigger: true
    passed: [deploy_staging]
  - get: gh-draft
  - task: smoke
    file: TodoApi/TodoApi.CI/smoke.yml
    timeout: 20m
    params:
      Endpoint: http://cnosal-todo-api-staging.cfapps.io
  - put: gh-release
    params:
      name: gh-draft/tag
      tag: gh-draft/tag
      globs:
      - gh-draft/todo-api.tar
      
- name: deploy_prod
  serial: true
  plan:
  - get: TodoApi
  - get: gh-release
    trigger: true
    passed: [smoke_staging]
  - task: unzip
    file: TodoApi/TodoApi.CI/unzip.yml
  - put: cloud-foundry-prod
    params:
      manifest: TodoApi-Publish/TodoApi.Deploy/cloud-foundry.yml
  