resources:
  - name: TodoApi
    type: git
    source:
      uri: https://github.com/xtreme-conor-nosal/dotnet-todo-rampup.git
      branch: master
      
  - name: cloud-foundry
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-email}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}

jobs:
- name: everything
  plan:
  - get: TodoApi
    trigger: true
  - task: build
    file: TodoApi/TodoApi.CI/build.yml
  - task: test
    file: TodoApi/TodoApi.CI/test.yml
  - put: cloud-foundry
    params:
      manifest: TodoApi-Publish/TodoApi.Deploy/cloud-foundry.yml